name: EAS Build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Install and build
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check npm version
        run: npm --version

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v4
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN_EXPO }}

      - name: Install eas-cli globally
        run: npm install -g eas-cli

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Build Android APK
        run: yarn eas build -p android --profile production --non-interactive --verbose